### ISSUE TITLE
Please add a license and screen shot

### ISSUE THREAD

**Issue by unixorn** [FDT2k/FDT2K-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Also, please add a license, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Please also consider naming the repository something more descriptive than oh-my-zsh-theme - even calling it FDT2k/FDT2K-theme would make it easier to keep track of once the user clones the repository locally.

**Comment by FDT2k** [comment]
All set. 

Thank you

**Comment by unixorn** [comment]
Added in https://github.com/unixorn/awesome-zsh-plugins/pull/806
